### ISSUE TITLE
ce of single char identifiers followed by punctuation consumes the punctuation

### ISSUE THREAD

**Issue by oblitum** [chaoren/vim-wordmotion#10]
When I do `ce` for `ab.` I get `.`, which is correct. If I do it for `a.` I get ` `, which is incorrect, the `.` gets consumed.

**Comment by chaoren** [comment]
This is one of the cases where you want to use `dw` instead.

`de` always deletes via the motion of `e`, inclusive.
```
[f]ooBar -> e -> fo[o]Bar
```
so
```
[f]ooBar -> de -> [B]ar
```
since `e` moves from `f` to `o`, `de` deletes from `f` to `o`, inclusive.

```
fo[o]Bar -> e -> fooBa[r]
```
since `o` is already the end of the word, so `e` must go to the *next* end of word, which is `r`.
Therefore
```
fo[o]Bar -> de -> f[o]
```
since `e` moves from `o` to `r`, `de` deletes from `o` to `r`, inclusive.

`dw` deletes with the motion of `w`, but exclusive, i.e., not including the last character.
So it would do what you want in your situation:
```
fo[o]Bar -> w -> foo[B]ar
```
so
```
fo[o]Bar -> dw -> fo[B]ar
```
since `w` moves from `o` to `B`, `dw` deletes from `o` to `B` excluding `B`.

You can argue that this is more complicated than the vim default, where you don't have to think about which one to use, and vim just adds a bunch of special cases to `dw` of what people usually want to do. And I'll kind of agree with you, but these special cases will make my plugin more complicated, less logical, and harder to maintain.

**Comment by oblitum** [comment]
😞 OK then. Thanks for the explanation.

**Comment by oblitum** [comment]
The sad thing is not having special cases in the software but instead, in my mind while editing code.
