### ISSUE TITLE
Why does word motion move to underscore first and then to the next word?

### ISSUE THREAD

**Issue by purpleP** [chaoren/vim-wordmotion#5]
Is there a good reason for that? Because for me it seems like a waste of my time.
And thank you for working on ```ci<leader>w```, because in the original plugin it doesn't work.

**Comment by chaoren** [comment]
The reason is that there's no good way to skip over underscores without introducing odd behavior.

If you really want such behavior, you can try this:
```
let g:wordmotion_extra = [ '_\+\zs\a\+' ]
```
but it will cause odd behavior at the beginning and end of words / lines / files.

If you come up with a better regex that still allows the plugin to be compatible in behavior to regular word motions, please let me know.

**Comment by chaoren** [comment]
I gave this some more thought. I think I have a way of making this work nicely.

**Comment by purpleP** [comment]
@chaoren I'll be glad to help.

**Comment by ninrod** [comment]
I'll be glad to help too. By the way, awesome plugin. You've made `ciw` correctly alter inner camel words out of the box. I just ditched the famous CamelCaseMotion in favor of your plugin. Happy customer here.

**Comment by chaoren** [comment]
Done. https://github.com/chaoren/vim-wordmotion/commit/8ffcb5db479edc45e1eb321b33747f8dc0ccd229

**Comment by purpleP** [comment]
@chaoren Thanks, if this works, I think my life have just become much easier!
