### ISSUE TITLE
#define is considered two words

### ISSUE THREAD

**Issue by MaxGyver83** [chaoren/vim-wordmotion#60]
I've just tried `vim-wordmotion`. What an awesome plugin!

But I was wondering about the strange stop points in this line:

```c
#define SCANCODE_TAB_KEY 15
^   ^   ^        ^   ^   ^
```

The reason might be that `#def` could be a short hex color code. Is this the intended behavior? I suppose there are more `#define`s in the world than mixed words starting with a short hex color code and going on with some unrelated letters :-)

Can I somehow define not to consider `#define` as two words? Kind of a blacklist?

**Comment by chaoren** [comment]
Yes, that was added for https://github.com/chaoren/vim-wordmotion/issues/48. Sorry.

I'm planning to fix it so that it would only recognize hex color codes if it ends with a word boundary. Unfortunately, `#define` will still be treated as two words in that case (`#` and `define`).

If `#` were a comment marker like `#this is a comment`, it would be kind of weird to include it in the first word of the comment.

Hard coding `#define`, `#ifdef`, and other C preprocessor directives would veer too much into language-specific territory, which I kind of don't want to support.

There's actually an undocumented option ([`g:wordmotion_extra`](https://github.com/chaoren/vim-wordmotion/blob/02e32fcb062553a8293992411677e12cacccb09d/autoload/wordmotion.vim#L68)) that lets you add extra word patterns. So you can use something like:
```vim
let g:wordmotion_extra = ['^#define\>', '^#ifdef\>']
```
or more generally:
```vim
let g:wordmotion_extra = ['#\w\+']
```

I left it undocumented because I didn't see a lot of people using it, but if more language-specific requests come in, I'll consider adding it to the documentation.

**Comment by MaxGyver83** [comment]
> There's actually an undocumented option (g:wordmotion_extra) that lets you add extra word patterns, so you can use something like:
> 
>     let g:wordmotion_extra = ['^#define\>', '^#ifdef\>']

This works. Thank you!
