### ISSUE TITLE
Hex color codes not recognized as single words

### ISSUE THREAD

**Issue by ShinyZero0** [chaoren/vim-wordmotion#73]
It's stated in README that the hex color codes are single words but e.g. #B2B2B2 is 6 words for me, same with lowercase. edit: That only happens when the color code is surrounded with quotes

**Comment by chaoren** [comment]
Okay, it seems to be treating `"#` as a separate word and skipping over that. Without the leading `#`, it won't recognize the rest of the color code as a word. I guess I'll need a way for "other printable characters" to get even lower priority. I'll probably need to find some more sophisicated way of doing this instead of using `search(...)`.

**Comment by chaoren** [comment]
I could call `searchpos(...)` twice for different word priorities. If they don't overlap choose whichever comes first. Otherwise, always choose the one with higher priority.
