### ISSUE TITLE
Support for hyphen, dot and sharp

### ISSUE THREAD

**Issue by lfmet** [chaoren/vim-wordmotion#8]
Actual (w motion):
```
[f]oo-bar
foo[-]bar
```

Expected:
```
[f]oo-bar
foo-[bar]
```

Can this be easily done? Maybe by extension.

**Comment by chaoren** [comment]
This is similar to #5, except that one is only about `_`.

My concern with `-` is things like this:
```
int a =[b]- c ;
int a = b -[c];
```
where you just skip over a semantically significant operator.

While `_` is usually semantically equivalent to a space character (e.g., in variable names), it's not the case for other symbols, so it doesn't feel right to just always treat them like spaces.

I can add a new configuration variable for the list of symbols you want to treat as spaces.
And maybe rework the regex so that these 'space-like' symbols behaves nicely around actual spaces.

E.g., `foo-bar` behaves like `[foo]-[bar]` and `foo - bar` behaves like `[foo] [-] [bar]`.
And maybe `foo  __init__  bar` should behave like `[foo] [__][init][__] [bar]`.

**Comment by lfmet** [comment]
I think `_` is the most _famous_ space character. Some examples:
- The hyphen is used in the lisp-family as a space and a lot in my native language (portuguese).
- The dot in javascript objects.
- The sharp in vimscript.

A configuration variable for a list of custom spaces would be great addition :))

This behavior `[foo] -[bar], [foo] __[init]__ [bar]` would solve _specific_ cases:
- The python example itself.
- Variables in perl/php (e.g. `$[x] [=] $[y]`).

**Comment by chaoren** [comment]
Added `g:wordmotion_spaces` option. Please let me know if it works for you.

**Comment by lfmet** [comment]
Works perfectly, thank you for the vim magic :))
