### ISSUE TITLE
I hope there could be an option to temporarily disable this plugin because sometimes I need to use the original word motion feature.

### ISSUE THREAD

**Issue by ian-ie** [chaoren/vim-wordmotion#80]

**Comment by chaoren** [comment]
You can `unmap` the keybinds as necessary and `:call wordmotion#reload()` to get them all back when you're done.

**Comment by chaoren** [comment]
Or just `nnoremap` the original motions to some other key.

**Comment by specious** [comment]
I was running into the same issue of wanting to use both the default and enhanced word motions.

This [comment on reddit](https://www.reddit.com/r/vim/comments/hsho8a/comment/fycenym/) gave me the idea of using a special prefix for accessing the enhanced motions, but it's somewhat difficult to find an easily-reachable prefix that doesn't conflict with anything.

Since I use `<Space>` as the leader key for a lot of combinations, I was able to use this solution:

```vimrc
" Protect default word motions by enabling enhanced motions under a special prefix
let g:wordmotion_prefix = '<Leader>w'
```

So now, the enhanced `daw` is `da<Space>ww`.

Not perfect, but better than losing the default functionality
